ThriftyNova updated to 2025
BroncBotz3481/YAGSL-Example pull request #263
Opened 2024-12-06 02:55 UTC by clrozeboom

2024-12-14 19:54 UTC, thenetworkgrinch commented
There have been alot of changes that this PR re-applies. Can you copy your ThriftyNova file over and make the necessary changes to `DeviceJson` then make a separate PR for your swerve drive test changes?

2024-12-14 20:50 UTC, clrozeboom commented
Whoops, yeah I've been trying to get this finalized so that it's out of my way. Is this better?

2024-12-17 19:57 UTC, thenetworkgrinch requested changes
Looks great! Just a little details that are needed. Thank you!

2024-12-17 19:57 UTC, thenetworkgrinch commented on src/main/java/swervelib/parser/json/DeviceJson.java
> +      case "thrifty_nova":
Needs one per motor type that can be attached to the Thrifty Nova. Should create the DCMotor here too.

2024-12-18 21:12 UTC, merged